# Parse all files with TypeScript.
extends:
  - 'standard-with-typescript'
  - 'prettier'

parserOptions:
  project: './tsconfig.json'
  createDefaultProgram: true

plugins:
  - prettier
  - react
  - '@typescript-eslint'
  - react-hooks

settings:
  react:
    version: detect

env:
  browser: true

rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: error
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars':
    - error
    - varsIgnorePattern: _
      argsIgnorePattern: _
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/consistent-type-definitions': off
